name: website
on:
  push:
    branches:
      - master
  pull_request:


jobs:
  build:
    name: Build website with quarto
    runs-on: ubuntu-latest
    container: mpetienne/maf:0.1

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install R packages
        run: |
          Rscript -e "install.packages(c('GGally'))"
      - name: Generate slides
        run: "quarto render"
      - name: GitHub Pages action
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
